
name: CI/CD

on: push

jobs:
  integration:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: integration
        run: |
          npm install --frozen-lockfile
          npm run validate
          npm run test
